//导航
export const GET_NAVIGATIONS='GET_NAVIGATIONS'

//切换导航
export const SWITCH_NAVIGATIONS='SWITCH_NAVIGATIONS'

//列表
export const GET_GAMELISTDATA='GET_GAMELISTDATA'
export const REQUEST_GAMELISTDATA='REQUEST_GAMELISTDATA'

//开盘
export const SWITCH_OPENING="SWITCH_OPENING"

//结束
export const SWITCH_FINISH="SWITCH_FINISH"
export const REQUEST_GAMEHISTORYLISTDATA='REQUEST_GAMEHISTORYLISTDATA'

//进度条
export const PROGRESS="PROGRESS"

//搜索
export const SEARCHACT="SEARCHACT"
export const CLEAR_SEARCH='CLEAR_SEARCH'

