//请求成功响应的标识
export	const	GETGAMEDETAIL_REQUEST	=	'GETGAMEDETAIL_REQUEST'
export	const	GETGAMEDETAIL_SUCCESS	=	'GETGAMEDETAIL_SUCCESS'
export	const	SWITCH_BANNER	=	'SWITCH_BANNER'
export	const	CLEAR_DETAIL	=	'CLEAR_DETAIL'
//点球成金动画的显示标识
export const PENALTY_BALL_ANIMATION = 'PENALTY_BALL_ANIMATION'

export const SHOW_FLAG = 'SHOW_FLAG'